// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13.03.2025, 20:33:52
const configMerger = require("C:/nuxtprojects/shptube/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/nuxtprojects/shptube/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/plugins/**/*.{js,ts,mjs}","C:/nuxtprojects/shptube/composables/**/*.{js,ts,mjs}","C:/nuxtprojects/shptube/utils/**/*.{js,ts,mjs}","C:/nuxtprojects/shptube/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/nuxtprojects/shptube/app.config.{js,ts,mjs}"] } }));

module.exports = config
